### ISSUE TITLE
下载 配置了gopath，NT环境报错

### ISSUE THREAD

**Issue by hiwoshixiaoyu** [liangdas/mqantserver#3]
panic: open F:\prj_my\mqantserver\src\server/bin/conf/server.json: The system cannot find the path specified.

goroutine 1 [running]:
github.com/liangdas/mqant/app.(*DefaultApp).Run(0xc042048640, 0xc0420ea001, 0xc0420ea000, 0x9, 0x9, 0xc042063ec8, 0x5189ab)
	F:/prj_my/gopath/src/github.com/liangdas/mqant/app/app.go:127 +0xe79
main.main()
	F:/prj_my/mqantserver/src/server/main.go:49 +0x3cf

**Comment by hiwoshixiaoyu** [comment]
F:\prj_my\mqantserver\bin>server.exe  --conf F:\prj_my\mqantserver\bin\conf\ser
ver.json 

NT需要这么做，才可以启动，请问怎么修改代码，才能直接调试

**Comment by zjjstart** [comment]
同问
